### ISSUE TITLE
Better project name :)

### ISSUE THREAD

**Issue by mjarkk** [mjarkk/vanmoof-web-controller#14]
This name is very generic and is not really advertisable
Lets get a better name

**Comment by sanderDijkxhoorn** [comment]
I was thinking about 

```

  ____  _ _        _               
 |  _ \(_) |      | |              
 | |_) |_| | _____| | ___  ___ ___ 
 |  _ <| | |/ / _ \ |/ _ \/ __/ __|
 | |_) | |   <  __/ |  __/\__ \__ \
 |____/|_|_|\_\___|_|\___||___/___/
                                   
```

As in bike.. less since you got more power options and speed options.

**Comment by sanderDijkxhoorn** [comment]
I think I like mooovi the most :)

but does look kinda similar to Moofer but still pretty good name.

**Comment by mjarkk** [comment]
`Moovy` it will be :)
