### ISSUE TITLE
Create a better looking share list for mobile

### ISSUE THREAD

**Issue by sanderDijkxhoorn** [mjarkk/vanmoof-web-controller#16]
![6F70F65C-B059-4D3A-BB22-851584C5BBEB](https://user-images.githubusercontent.com/15117158/175275142-484704db-efe0-4a0c-a3ee-8b92820dab38.jpeg)

Some padding at the left and right side might even do the job but would look bad for a longer e-mail adress.

**Comment by mjarkk** [comment]
This should be fixed now:
![image](https://user-images.githubusercontent.com/15320763/175768490-5af4ba13-0ec9-439c-897e-3a2fd9c390ca.png)
