### ISSUE TITLE
Share bike forever

### ISSUE THREAD

**Issue by sanderDijkxhoorn** [mjarkk/vanmoof-web-controller#17]
We could also add a option to the slider if you slide all the way to the right it will share forever, to share a bike for ever the bike uses the following request body:

`
{
  "email" : "here@the.email",
  "role" : "user",
  "bikeId" : herethebikeidasnumber
}`

**Comment by mjarkk** [comment]
It should now be possible to drag the duration slider to the end and the share duration will be unlimited :)
