### ISSUE TITLE
Latest patch?

### ISSUE THREAD

**Issue by jeffreymooiweer** [mjarkk/vanmoof-web-controller#2]
Does this work with the latest patch 1.8.1?

**Comment by mjarkk** [comment]
Not sure, my bike has version 1.7.6 and i still want to drive 37 km/h so not gonna test it on my own bike  

As i have based the code on [pymoof](https://github.com/quantsini/pymoof) and they have [an issue about version 1.8.1 not working](https://github.com/quantsini/pymoof/issues/7) it might be that this version doesn't work :(

**Comment by thomasbaetge** [comment]
see my comment on pymoof. It still works with 1.8.1 but after a day of bike inactivity, the function will be limited until you wake the bike up.
I assume, this is the result of the frequently reported battery drain issues over the winter (caused probably by the BT module)

**Comment by mjarkk** [comment]
Thanks for the information!  
I've added a hint to press the bike's wake button if bluetooth connecting works but authentication fails
