### ISSUE TITLE
Does this tool still work on version v1.8.2?

### ISSUE THREAD

**Issue by mjarkk** [mjarkk/vanmoof-web-controller#22]
I recently noticed people talking about version v1.8.2 and I was wondering if that still work with this tool.
My own bike is still on v1.7.6 and I don't want to loose the fastest speed option (yet).

**Comment by jericho1ne** [comment]
I noticed these two options are disabled under 1.8.2 - so I assume there is work to be done :)
<img width="484" alt="Screen Shot 2022-07-02 at 8 55 33 AM" src="https://user-images.githubusercontent.com/2898976/177007697-4f936eb8-81c4-442c-aeec-926f943187bc.png">

**Comment by jericho1ne** [comment]
Curious if I can assist in any way. `PowerLevel(Max)` and `SpeedLimit(NO_LIMIT)` both seem to return the previously selected values - seems as if the firmware simply refuses to do your bidding :)

```
export enum PowerLevel {
    Off = 0,
    First = 1,
    Second = 2,
    Third = 3,
    Fourth = 4,
    Max = 5,
}

export enum SpeedLimit {
    JP = 2,
    EU = 0,
    US = 1,
    NO_LIMIT = 3,
}
```

**Comment by sanderDijkxhoorn** [comment]
> Curious if I can assist in any way. `PowerLevel(Max)` and `SpeedLimit(NO_LIMIT)` both seem to return the previously selected values - seems as if the firmware simply refuses to do your bidding :)
> 
> 
> 
> ```
> 
> export enum PowerLevel {
> 
>     Off = 0,
> 
>     First = 1,
> 
>     Second = 2,
> 
>     Third = 3,
> 
>     Fourth = 4,
> 
>     Max = 5,
> 
> }
> 
> 
> 
> export enum SpeedLimit {
> 
>     JP = 2,
> 
>     EU = 0,
> 
>     US = 1,
> 
>     NO_LIMIT = 3,
> 
> }
> 
> ```

![image](https://user-images.githubusercontent.com/15117158/177010235-0adb26da-a677-4027-aa6d-8558cf03a07b.jpeg)

I am not sure if we can do anything about this as of now. We are looking into downgraden/upgrading #6

**Comment by mjarkk** [comment]
@jericho1ne Thanks for confirming the site still works with the features the bike exposes to us.

I think we should disable the 37km/h option and assistance level 5 if the bike's firmware is above v1.8 because when they are visible users think they can use that and be confused when it doesn't work

**Comment by stefanstranger** [comment]
Just to tested 1.8.2 firmware with the following result.

![Screenshot_20220710-175527](https://user-images.githubusercontent.com/2125385/178152246-7d0f0e86-eb9a-4b34-a99b-dadbd86626d1.jpg)

Cannot save option for 37 km and gear 5 options. Could change speed from 25 to 32 km.

**Comment by sanderDijkxhoorn** [comment]
> Just to tested 1.8.2 firmware with the following result.
> 
> 
> 
> ![Screenshot_20220710-175527](https://user-images.githubusercontent.com/2125385/178152246-7d0f0e86-eb9a-4b34-a99b-dadbd86626d1.jpg)
> 
> 
> 
> Cannot save option for 37 km and gear 5 options. Could change speed from 25 to 32 km. 
> 
> 

We are aware of this, we will add a check if you are above version 1.8 these features will be removed.

**Comment by stefanstranger** [comment]
Would it also be possible to change the bell sound using one of your sounds?

**Comment by sanderDijkxhoorn** [comment]
> Would it also be possible to change the bell sound using one of your sounds?

Do you mean is it possible to set a custom bell sound?  Well you can use the 3 default bells + 1 Easter egg boat bell. Currently it is not possible to set a custom bell sound.

**Comment by stefanstranger** [comment]
And how to I set the Easter-egg boat horn?

**Comment by sanderDijkxhoorn** [comment]
> And how to I set the Easter-egg boat horn?

Oh I didn't knew we have not add that to the web app, currently you can set it trough the Moofer app made by Quinten (paid) or we would have to add it to the app or web app. (I would have to look how I can log bluetooth on my Macbook if I wanna add it myself)

**Comment by sanderDijkxhoorn** [comment]
> And how to I set the Easter-egg boat horn?

I am gonna try my best now, I don't have any experience with sending and logging the bluetooth requests. The horns are probably gonna give me headache but I will try my best. :)

**Comment by sanderDijkxhoorn** [comment]
I am currently missing 1 bell tone but I couldn't figure out how to add the submarine yet... :!

**Comment by sanderDijkxhoorn** [comment]
@stefanstranger can you try this:
[My PR with bells added](https://vanmoof-web-controller-git-fork-sanderdijkxhoorn-bells-mkopenga.vercel.app)

**Comment by stefanstranger** [comment]
Just configured the boat horn!

![image](https://user-images.githubusercontent.com/2125385/179353496-1e325917-c7ae-4ded-a323-94b6e57620d3.png)

Let me test if this is now working later today when I'm on a bike ride :-)

**Comment by stefanstranger** [comment]
And this what I now see in the original vanMoof app. So it seems that a new horn can be configured. 
![Screenshot_20220716-140255](https://user-images.githubusercontent.com/2125385/179354184-d42ba313-d2cd-41d3-8d4e-96983770e406.jpg)

**Comment by sanderDijkxhoorn** [comment]
> And this what I now see in the original vanMoof app. So it seems that a new horn can be configured. 
> 
> ![Screenshot_20220716-140255](https://user-images.githubusercontent.com/2125385/179354184-d42ba313-d2cd-41d3-8d4e-96983770e406.jpg)
> 
> 

👍 I will add the submarine bell as well when I get home. 😃

**Comment by stefanstranger** [comment]
Tested when riding my bike and the new boat horn works like a charm. Thanks for enabling this feature.

**Comment by sanderDijkxhoorn** [comment]
> Tested when riding my bike and the new boat horn works like a charm. Thanks for enabling this feature. 

👍

No problem :)

**Comment by stefanstranger** [comment]
Is the PR already merged in main?

**Comment by sanderDijkxhoorn** [comment]
> Is the PR already merged in main?

Yes :)

**Comment by Abandoned101** [comment]
Hi hoping some one can help me get this connected to my bike?  Shop updated the firmware(gutted) I've followed the link and signed in and selected my bike but nothing happens.

**Comment by sanderDijkxhoorn** [comment]
> Hi hoping some one can help me get this connected to my bike?  Shop updated the firmware(gutted) I've followed the link and signed in and selected my bike but nothing happens. 

Hi,

Which firmware version are you on now?

With the latest firmware versions you can no longer set the 37 kmph & assist 5 mode.

**Comment by Abandoned101** [comment]
> 

Yeah am now on 1.8.1 and gutted they updated it was the most depressing ride home ever. Am also on the EU settings so was hoping to atleast be able set it to US

**Comment by sanderDijkxhoorn** [comment]
> > 
> 
> 
> 
> Yeah am now on 1.8.1 and gutted they updated it was the most depressing ride home ever. Am also on the EU settings so was hoping to atleast be able set it to US 

The US option should be working, doesn't it?

**Comment by Abandoned101** [comment]
> > > 
> > 
> > 
> > Yeah am now on 1.8.1 and gutted they updated it was the most depressing ride home ever. Am also on the EU settings so was hoping to atleast be able set it to US
> 
> The US option should be working, doesn't it?

This is all I see
![Screenshot_20220804-202544_Samsung Internet](https://user-images.githubusercontent.com/110627818/182936357-277284e5-bdfd-4088-98f5-c3307e44e239.jpg)

**Comment by Abandoned101** [comment]
> 
Nothing just highlights it blue as shown in the picture

**Comment by sanderDijkxhoorn** [comment]
> > 
> 
> Nothing just highlights it blue as shown in the picture 
> 
> 

Which browser do you use and do you know if it supports Bluetooth?

**Comment by Abandoned101** [comment]
> > > 
> > 
> > 
> > Yeah am now on 1.8.1 and gutted they updated it was the most depressing ride home ever. Am also on the EU settings so was hoping to atleast be able set it to US
> 
> The US option should be working, doesn't it?

I didn't have permissions on! 🤦‍♀️ your a legend thank you! 
Do you think you'll be able to get past the block on power assist 5 and the speed restrictions?

**Comment by sanderDijkxhoorn** [comment]
> > > > 
> 
> > > 
> 
> > > 
> 
> > > Yeah am now on 1.8.1 and gutted they updated it was the most depressing ride home ever. Am also on the EU settings so was hoping to atleast be able set it to US
> 
> > 
> 
> > The US option should be working, doesn't it?
> 
> 
> 
> I didn't have permissions on! 🤦‍♀️ your a legend thank you! 
> 
> Do you think you'll be able to get past the block on power assist 5 and the speed restrictions? 

I don't think it is possible to get it working on the latest firmware since they removed it. Currently the only way we think would be possible is by downgrading/fake upgrading to an older version which still has the features or using an custom firmware.

**Comment by Abandoned101** [comment]
> > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > Yeah am now on 1.8.1 and gutted they updated it was the most depressing ride home ever. Am also on the EU settings so was hoping to atleast be able set it to US
> > 
> > 
> > > 
> > 
> > 
> > > The US option should be working, doesn't it?
> > 
> > 
> > I didn't have permissions on! 🤦‍♀️ your a legend thank you!
> > Do you think you'll be able to get past the block on power assist 5 and the speed restrictions?
> 
> I don't think it is possible to get it working on the latest firmware since they removed it. Currently the only way we think would be possible is by downgrading/fake upgrading to an older version which still has the features or using an custom firmware.

Thought this might be the case. Well thank you for all your efforts wish I could help in some way

**Comment by sanderDijkxhoorn** [comment]
> > > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > Yeah am now on 1.8.1 and gutted they updated it was the most depressing ride home ever. Am also on the EU settings so was hoping to atleast be able set it to US
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > The US option should be working, doesn't it?
> 
> > > 
> 
> > > 
> 
> > > I didn't have permissions on! 🤦‍♀️ your a legend thank you!
> 
> > > Do you think you'll be able to get past the block on power assist 5 and the speed restrictions?
> 
> > 
> 
> > I don't think it is possible to get it working on the latest firmware since they removed it. Currently the only way we think would be possible is by downgrading/fake upgrading to an older version which still has the features or using an custom firmware.
> 
> 
> 
> Thought this might be the case. Well thank you for all your efforts wish I could help in some way 

If you would like contribute to the project you could check out PR #19, we are currently working on a flutter app version. Thanks for confirming that 1.8.1 still works. If you know more about the firmware downgrading/upgrading process or anything else feel free to join our [discord server](https://discord.gg/gQFC2n7Tc9).

**Comment by bjhollingsworth** [comment]
Confirmed working with 1.8.2 (using Bluefy) - got my fingers crossed for a way to re-instate 37kph/5th gear but in the meantime, thanks SO much for getting me away from 16MPH hell!

**Comment by alexsorel** [comment]
Confirm it works on 1.8.2 (S3), Android with Chrome. But no display of 37 km/h nor level 5.

**Comment by sanderDijkxhoorn** [comment]
> Confirm it works on 1.8.2 (S3), Android with Chrome. But no display of 37 km/h nor level 5.

Like FAQ says, since version 1.8.1 or above those modes have been removed from the bike firmware.

**Comment by attilatdeak** [comment]
The tool itself works fine even with 1.9.3. The offroad mode and level 5 are removed on firmware level.
