### ISSUE TITLE
No Compatible devices found

### ISSUE THREAD

**Issue by stefanstranger** [mjarkk/vanmoof-web-controller#30]
I'm getting no compatible devices found message when trying to connect to my vanMoof S3. Sometimes I'm able to connect other times I'm getting above message.

![image](https://user-images.githubusercontent.com/2125385/179351706-4b3a46b6-298c-4c3b-bbdd-2a011651c51a.png)

Bike is unlocked and I can connect via the vanMoof app to the bike.

Any ideas how to resolve this?

Regards,
Stefan

**Comment by sanderDijkxhoorn** [comment]
> I'm getting no compatible devices found message when trying to connect to my vanMoof S3. Sometimes I'm able to connect other times I'm getting above message.
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/2125385/179351706-4b3a46b6-298c-4c3b-bbdd-2a011651c51a.png)
> 
> 
> 
> Bike is unlocked and I can connect via the vanMoof app to the bike.
> 
> 
> 
> Any ideas how to resolve this?
> 
> 
> 
> Regards,
> 
> Stefan

Do you have a device connected to your bike while you are doing this? (You can only connect 1 device to the bike at the same time)

**Comment by mjarkk** [comment]
This is probably due to the crappy bluetooth web api support by many browsers. You could try Chrome but this seems to me like an issue we can't fix :(

That said we are working on an android / iOS app that should be way better in regards to bike connection #19

**Comment by stefanstranger** [comment]
When disconnecting the original vanMoof app from my mobile it was able to connect via the browser. Was not aware only one device could be connected.

Solved.
