### ISSUE TITLE
Where does the API_KEY come from?

### ISSUE THREAD

**Issue by Marius-Elting** [mjarkk/vanmoof-web-controller#44]
https://github.com/mjarkk/vanmoof-web-controller/blob/7ea8e8b29e7a5e89d382d79a1530796d4250eb76/lib/api.ts#L4

there is an API_KEY, wich is required to login / use the Vanmoof API.

where can I get my own or is this an universal one?

2. Is there any Documentation or similar for the Vanmoof API, I can't find one on the Internet.

**Comment by sanderDijkxhoorn** [comment]
> https://github.com/mjarkk/vanmoof-web-controller/blob/7ea8e8b29e7a5e89d382d79a1530796d4250eb76/lib/api.ts#L4
> 
> there is an API_KEY, wich is required to login / use the Vanmoof API.
> 
> where can I get my own or is this an universal one?
> 
> 2. Is there any Documentation or similar for the Vanmoof API, I can't find one on the Internet.

This is baked into the VanMoof app.

**Comment by mjarkk** [comment]
To add to that it's also used by all other vanmoof open source project and vm doesn't seem to have a problem with it thus far.
