### ISSUE TITLE
Support for firmware update 1.9.1

### ISSUE THREAD

**Issue by stefanstranger** [mjarkk/vanmoof-web-controller#46]
For my S3 I see a firmware update with version 1.9.1

Will Mooovy.app still work after this firmware update?

Regards,
Stefan

**Comment by sanderDijkxhoorn** [comment]
I would assume it would, you won’t be able to access the 37 KMPH option tho.

**Comment by pponce** [comment]
@stefanstranger 
How did you get firmware 1.9.1 for S3?
Do you have any information on what was updated or changed?

My S3 says it has the latest firmware and is version 1.8.2.
Very curious about this new firmware.

**Comment by pponce** [comment]
Also @sanderDijkxhoorn Is there a way to capture this new firmware for others to install?

**Comment by sanderDijkxhoorn** [comment]
> Also @sanderDijkxhoorn Is there a way to capture this new firmware for others to install?

There is a way to capture it not sure about installing, you might be able to intercept the download and replace the download with your custom download you want. 

I made a branch to intercept it not sure if I got up online I might be able to share it later but might not be doable this week.

**Comment by pponce** [comment]
No rush. Glad you captured it!
Would be great if it were possible to upgrade to it our selves. Any idea what was updated? Fixed?

**Comment by sanderDijkxhoorn** [comment]
> No rush. Glad you captured it!
> Would be great if it were possible to upgrade to it our selves. Any idea what was updated? Fixed?

I have no idea, I am still on a old firmware version, the updates should have changelogs.

**Comment by stefanstranger** [comment]
If you want to know what the latest available firmware is you can just call this REST API

```bash
curl  -X GET   'https://my.vanmoof.com/api/v8/getDesiredUpdateVersionInfo/68713'   --header 'Accept: */*'   --header 'Api-Key: fcb38d47-f14b-30cf-843b-26283f6a5819'   --header 'Authorization: Bearer <access token>' | jq -r
```

![image](https://github.com/mjarkk/vanmoof-web-controller/assets/2125385/33e0daa7-9820-4000-a5b6-c7e7da5195d7)

**Comment by pponce** [comment]
I’m very new to this project but will spend some time to figure out how to do this.
Is there anyway to trigger a firmware update for my s3? The app says I’m on the latest version but obviously not. Would like to apply the improvements for the battery function to avoid drain.

**Comment by attilatdeak** [comment]
Its workng with 1.9.3 too. For bt commands there is no change.

**Comment by nicosandller** [comment]
Updated to `1.9.3` and was able to confirm the bike is still running the same configuration I had with 32 km/h max and boost button!

**Comment by mjarkk** [comment]
Good to hear everything still works on firmware 1.8.3
