### ISSUE TITLE
Can't set speed to 37km/h

### ISSUE THREAD

**Issue by travigd** [mjarkk/vanmoof-web-controller#5]
I'm not sure if this is a bike model/firmware thing, but I can't set my bike above the US setting (though I can set it to the EU/JP settings). Clicking the 37 button just switches back to the 32 after a second and the bike itself doesn't seem to register the change.

Looking at the bike data, it might be fixed into the bike model itself. Posting here mostly just in case anyone else comes across this.

```
{
  "modelDetails": {
    "Gears": "Automatic 4 speed shifting gears",
    "Motor": "250 - 500 W front-wheel hub motor",
    "Top Speed": "20 mph (US speed)",
    "Range": "60 km (full power) ~ 150 km (economy mode)",
    "Edition": "ES-3 4G",
    "Connectivity": "4G"
  },
  "modelName": "VM01-203-US"
}
```

**Comment by akucharczyk** [comment]
Which Firmware do you have @travigd? Vanmoof removed this option at version 1.8.0. So you need 1.7.6 or lower for the 37km/h mode

**Comment by mjarkk** [comment]
I suspect @akucharczyk is right and i cannot do anything about that :(.  
Closing this issue for now, tough if this is not the case feel free to re-open the issue
