### ISSUE TITLE
need to delete my account

### ISSUE THREAD

**Issue by johnyvino** [mjarkk/vanmoof-web-controller#50]
need to delete my account

**Comment by sanderDijkxhoorn** [comment]
How is this a issue with our app?

**Comment by sanderDijkxhoorn** [comment]
If you delete your account:
- You won’t have access to your past invoices, so make sure to save a copy for any future warranty. 
- You won’t have access to your repair history

What to do before you can delete your account 
- Remove yourself as the owner of the bike. [Read how to do this here](https://support.vanmoof.com/en/support/solutions/articles/44002128466-how-can-i-change-the-owner-of-my-bike-).
- Remove any shared riders from your bike. [Read how to do this here](https://support.vanmoof.com/en/support/solutions/articles/44002259863-bike-sharing).

It can take up to 30 days until the process is complete.

If you still want to permanent delete your VanMoof account go to:
https://www.vanmoof.com/my-vanmoof/en/profile
Login -> Go to your profile -> scroll down and click permanently delete.

**Comment by johnyvino** [comment]
I want to delete the acccont, login detail I created for your app. I am cosoiuos getting getting of my privacy online. thank you for yout herlp

**Comment by mjarkk** [comment]
Open dev tools and remove all local storage.. that's all the information we have.
