### ISSUE TITLE
Flutter app - Authentication failed on macOS and Android

### ISSUE THREAD

**Issue by TimTheBeastNL** [mjarkk/vanmoof-web-controller#51]
I'm currently developing an app and I'm using the flutter project as base / reference for my app. Now I came across an issue with the authentication on macOS and Android. Every time you try to login with your credentials it doesn't work and gives me the error "Authentication failed".  Looking at the network traffic it doesn't even reach the VanMoof Servers.

**Comment by playmiel** [comment]
maybe a prolem with cors

**Comment by mjarkk** [comment]
The flutter app was a work in progress. I think that was not implemented or wrongly implemented.

Maybe i will soon start working again on the app but will start over again as i'm not happy with the code.

Closing this issue for now as the app was a wip.
