### ISSUE TITLE
VanMoof S3 Bluetooth connection died

### ISSUE THREAD

**Issue by KEESS3** [mjarkk/vanmoof-web-controller#54]
After fine working since june 2020 and 22k km's my bluetooth died. Reset bike or app did not help. It probably has to do with the bluetooth key or otherwise something like that. I have all the data from the bike like MAC, encryptionkey etc...anybody knowing the exact reason? anybody knowing how to solve this?

**Comment by sanderDijkxhoorn** [comment]
> After fine working since june 2020 and 22k km's my bluetooth died. Reset bike or app did not help. It probably has to do with the bluetooth key or otherwise something like that. I have all the data from the bike like MAC, encryptionkey etc...anybody knowing the exact reason? anybody knowing how to solve this?

I don't understand what this has to do with Mooovy. You can't connect to the bike at all, what is the exact problem you are experiencing?

**Comment by KEESS3** [comment]
the question is if anybody has an idea how to reastablish the connection? and if so just next step is to use mooovy.

**Comment by sanderDijkxhoorn** [comment]
> the question is if anybody has an idea how to reastablish the connection? and if so just next step is to use mooovy.

If you are unable to connect to the official VanMoof app it seems more like a hardware issue. I recommend contacting VanMoof support or one of their new official partners

**Comment by KEESS3** [comment]
vanmoof support is not reachable anylonger since last summer 2023 they were bankrupt.
And bytheway this is most likele an issue with the bluetooth key, many users complain about this, see on reddit,
The solution vanmoof gives in the app when not connected is delete the bike from your account and register again, probably the key is renewed than, but i am afraid than my speed setting will go back to the max 25km/h while it now still is on 32km/h

**Comment by sanderDijkxhoorn** [comment]
> vanmoof support is not reachable anylonger since last summer 2023 they were bankrupt.
> 
> And bytheway this is most likele an issue with the bluetooth key, many users complain about this, see on reddit,
> 
> The solution vanmoof gives in the app when not connected is delete the bike from your account and register again, probably the key is renewed than, but i am afraid than my speed setting will go back to the max 25km/h while it now still is on 32km/h

That is not true, I had a conversation with their support team about a week ago. Who cares just set your speed back to 32 after re-adding the bike back to your account?

**Comment by KEESS3** [comment]
Okay if that is true it might be a solution to delete the registration and create it again.
My question: how did you get in contact with vanmoof support team?

**Comment by sanderDijkxhoorn** [comment]
> Okay if that is true it might be a solution to delete the registration and create it again.
> 
> My question: how did you get in contact with vanmoof support team?

You can just sent them a DM on Instagram, FB messenger or trough a request.

**Comment by KEESS3** [comment]
Hello Sander and all Riders good news! After 5 days down. My bluetooth came alive this morning15may24 at 7oclock. The S3 powered on automatic. I was planning but did not dear yet to disable/enable my registration, glad i did not yet. Probably the vanmoof management has reset cleaned up the database or something like that. Probably goodnews for other riders with a simular problem too, let me know thanks. If this was a setup action by the vanmoof engineers than thanks a lot for that, if they read this let me know please. The only minuspoint is that the ridesoverview is empty but thats not a big issue. for the rest i could switch my dingdong back on, the gear setting on my own setting, and the light automatic, the speed setting was anyway still on 32km/h all the time even with bluetooth down. I am fully back on the ride now thanks a lot!

**Comment by KEESS3** [comment]
correction the rides are still there, i did not look good..

**Comment by mjarkk** [comment]
It might be your bluetooth chip is corrupt or broken.
There are some repair shops here in the Netherlands at least that can fix some of those problems.

Anyway i will also close this issue as it doesn't have much todo with this repo.
