### ISSUE TITLE
Can't connect to bike.

### ISSUE THREAD

**Issue by sanderDijkxhoorn** [mjarkk/vanmoof-web-controller#7]
Hi,

Is there any way to contact you on a platform like Discord? (I own 3 bikes 2x S3 & 1x X3 and I would love to help with this project)

**Comment by mjarkk** [comment]
Help is always appreciated, my discord username is: `ʞʞɹɐɾɯ#1220`

**Comment by sanderDijkxhoorn** [comment]
> Any chance you could share your discord with me too please? Once I've connected it to your app, I can no longer connect to the official app. Is that normal? Any set steps I need to follow when switching between the two?

Well you can’t connect using multiple apps at the same time if you press disconnect on the dashboard or close the app you are still not able to connect with the official app?

**Comment by Nelinski** [comment]
Weirdly, I had to reset the bike to pair back with the official app. But the settings remained. I'll keep playing with it thanks!

**Comment by sanderDijkxhoorn** [comment]
> Weirdly, I had to reset the bike to pair back with the official app. But the settings remained. I'll keep playing with it thanks!

@Nelinski hmm weird, let me know if you found out why :)
