### ISSUE TITLE
[Feature Request] Progressive Web App Support

### ISSUE THREAD

**Issue by Nelinski** [mjarkk/vanmoof-web-controller#8]
A nice to have feature would be progressive web app support so you can "install" the app on your phone like a normal app so it's easier to find/use. Thanks for the site either way, it's great.

**Comment by mjarkk** [comment]
That would be a nice addition.

For that we'll need 2 things:
- [ ] Site icon
- [ ] Add a service worker

**Comment by mjarkk** [comment]
It should now be possible, after a reload and connecting to my bike the install button appeared in my browser.
![image](https://user-images.githubusercontent.com/15320763/175769299-c18952b2-b642-4207-a946-06f50662f03a.png)
